### ISSUE TITLE
Action not received by JS

### ISSUE THREAD

**Issue by sGerli** [r-dent/pebble-analytics#4]
I'm using pebble-events package.
Your appmessage is not getting out of my app and I'm not getting any error.
It would be great if you converted this into a [Pebble Package](https://developer.pebble.com/guides/pebble-packages/creating-packages/) and make it easy for people to setup now that Pebble analytics are down and probably will never be back.

**Comment by r-dent** [comment]
Hi @sGerli,
sounds like a good idea. i will look into it as soon as possible.

**Comment by r-dent** [comment]
"Your appmessage is not getting out of my app and I'm not getting any error."
@sGerli What do you mean with that? Are there no requests sent?

**Comment by sGerli** [comment]
I meant that the request wasn't getting to the JS and neither to GA but that might be a problem with my setup because I am using pebble-events https://www.npmjs.com/package/pebble-events to manage the app-message subscription

**Comment by sGerli** [comment]
I found my issue, my issue gives me this error:
```
pkjs> Error: Can't interact with the watch before the ready event is fired.
	at getAccountToken ((eval))
	at Analytics (pebble-js-app.js:946:31)
	at pebble-js-app.js:95:11
	at __webpack_require__ (pebble-js-app.js:20:30)
	at pebble-js-app.js:48:19
	at __webpack_require__ (pebble-js-app.js:20:30)
	at pebble-js-app.js:40:18
	at pebble-js-app.js:43:10

```
And it gets fixed if I put ` var ga = new Analytics([all of this things]);` inside of the ready event.
